name: Build and Test

on:
  push:
    branches: [ dev ]
    paths-ignore:
      - "**.md"
      - "**.ps1"
      - ".editorconfig"
      - "TestFiles/*"
      - '**/*.gitignore'
      - '**/*.gitattributes'
      - '**/*.yml'
  pull_request:
    branches: [ dev, main ]

  # allow running this workflow manually
  workflow_dispatch:

jobs:
  build:
    name: Build and Test
    # use ubuntu-latest image to run steps on
    runs-on: windows-latest

    steps:
      # uses GitHub's checkout action to checkout code form the release branch
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Build android project
        uses: igotinfected-ci/build-monogame@v2.0.3
        with:
          solution-path: '${{ github.workspace }}\MonoGameUdemyCourseSolution.sln'
          content-mgcb-path: '${{ github.workspace }}\IntroGraphics\Content'
          content-mgcb-platform: "Windows"
          csproj-path: '${{ github.workspace }}\IntroGraphics\IntroGraphics.csproj'
          build-target: "PackageForWindows"
          build-configuration: "Release"
