name: Publish to Itch.io

on:
  push:
    tags:
    - 'v*'

env:
  ITCH_USER_NAME: codemonkey85
  ITCH_GAME_NAME: monogametest
  PROJECT_PATH: IntroGraphics

jobs:
  build:
    name: Build and Test
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    env:
      MGFXC_WINE_PATH: /home/runner/.winemonogame

    steps:
      # uses GitHub's checkout action to checkout code form the release branch
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      # sets up .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v4.2.0

      - name: Get version from tag
        run: |
          TAGVERSION=$(git describe --tags --abbrev=0)
          echo "TAGVERSION=${TAGVERSION:1}" >> $GITHUB_ENV

      - name: Setup Wine
        run: |
          sudo apt update
          sudo apt install wine64 p7zip-full
          wget -qO- https://raw.githubusercontent.com/MonoGame/MonoGame/78636f8056fa981584e3a2a3e0f22e2efbc43ef8/Tools/MonoGame.Effect.Compiler/mgfxc_wine_setup.sh | sh

      - name: Build Windows
        run: dotnet publish ${{ env.PROJECT_PATH }} -r win-x64 -c Release --self-contained --output artifacts/windows

      - name: Build Osx
        run: dotnet publish ${{ env.PROJECT_PATH }} -r osx-x64 -c Release --self-contained --output artifacts/osx

      - name: Build Linux
        run: dotnet publish ${{ env.PROJECT_PATH }} -r linux-x64 -c Release --self-contained --output artifacts/linux

      - name: Publish Windows build to itch.io
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: windows
          ITCH_GAME: ${{ env.ITCH_GAME_NAME }}
          ITCH_USER: ${{ env.ITCH_USER_NAME }}
          PACKAGE: artifacts/windows
          VERSION: ${{ env.TAGVERSION }}
      - name: Publish OSX build to itch.io
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: osx
          ITCH_GAME: ${{ env.ITCH_GAME_NAME }}
          ITCH_USER: ${{ env.ITCH_USER_NAME }}
          PACKAGE: artifacts/osx
          VERSION: ${{ env.TAGVERSION }}
      - name: Publish Linux build to itch.io
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: linux
          ITCH_GAME: ${{ env.ITCH_GAME_NAME }}
          ITCH_USER: ${{ env.ITCH_USER_NAME }}
          PACKAGE: artifacts/linux
          VERSION: ${{ env.TAGVERSION }}
  